messages:
  carbohydrates: "Glucides"
  carbohydrates-colour: "&e"
  proteins: "Protéines"
  proteins-colour: "&c"
  vitamins: "Vitamines"
  vitamins-colour: "&a"
  water: "Hydratation"
  water-colour: "&b"
  cold: "Froid"
  cold-color: "&b"
  only-in-game: "&c[!!] Only in-game players can perform this command!"
  usage-reset: "&c[!!] Usage: /fb reset <player>"
  values-reset: "&aThe values of &6%player%&a have been reset!"
  reload-ok: "&aReloaded FoodBalance %version%."
  reload-fail: "&cFailed reloading FoodBalance %version%."
  death-cold: "%player% est mort de froid"
  death-hydration: "%player% est mort de soif"
  death-carbohydrates-lack: "%player% died due to a lack of carbohydrates"
  death-carbohydrates-much: "%player% ate too much carbohydrates and died"
  death-vitamins-lack: "%player% died due to a lack of vitamins"
  death-vitamins-much: "%player% ate too much vitamins and died"
  death-proteins-lack: "%player% died due to a lack of proteins"
  death-proteins-much: "%player% ate too much proteins and died"
#- FOOD_NAME,VITAMINS,PROTEINS,CARBOHYDRATES,WATER
foods: ['MILK_BUCKET,0,0,0,900','POTION,0,0,0,900','DRIED_KELP,0,0,2,0','PUFFERFISH,0,2,0,0','TROPICAL_FISH,0,2,0,0','SALMON,0,2,0,0','COD,0,2,0,0','ROTTEN_FLESH,0,2,0,0','COOKIE,0,0,3,0','MELON,3,0,2,75','POISONOUS_POTATO,0,0,2,0','BEETROOT_SOUP,0,0,2,50','BEETROOT,0,0,2,50','POTATO,0,0,2,0','CHICKEN,0,2,0,0','PORKCHOP,0,2,0,0','BEEF,0,2,0,0','APPLE,1,0,1,25','PUMPKIN_PIE,0,0,2,0','CARROT,2,0,0,0','BREAD,0,0,2,0','MUSHROOM_STEW,0,0,2,50','COOKED_CHICKEN,0,2,0,0','BAKED_POTATO,0,0,2,0','SPIDER_EYE,0,2,0,0','MUTTON,0,2,0,0','COOKED_MUTTON,0,2,0,0','RABBIT_STEW,0,2,0,50','RABBIT,0,2,0,0','COOKED_RABBIT,0,2,0,0','COOKED_SALMON,0,2,0,0','COOKED_COD,0,2,0,0','COOKED_BEEF,0,2,0,0','COOKED_PORKCHOP,0,2,0,0','GOLDEN_APPLE,1,0,1,25','GOLDEN_CARROT,0,0,0,0']