name: FoodBalance
main: nl.SugCube.FoodBalance.Main.FoodBalance
version: '1.2'
description: >
             Be aware of your eat-stuff!
commands:
  health:
    description: Shows your FoodBalance-stats