name: FoodBalance
main: nl.SugCube.FoodBalance.FoodBalance
version: '2.0'
authors: [MrSugarCaney]
description: >
             Be aware of your eating!
commands:
  health:
    description: Shows your FoodBalance-stats
    aliases: [food, foodstats, fbstats, fbalancestats, foodbalancestats]
  foodbalance:
    description: Main command of FoodBalance
    aliases: [fb, foodb, fbalance]